// utils/deptDB.js
export const departments = [
  {
    id: 1,
    name: "Pastoral Care",
    president: "Rev. John Doe",
    est: "2001",
    description: "Guiding spiritual growth and providing pastoral support.",
    members: ["Obed", "Eric", "Grace", "Mary"],
    committee: [
      { role: "President", name: "Obed" },
      { role: "Vice President", name: "Eric" },
      { role: "Secretary", name: "Grace" },
      { role: "Treasurer", name: "Mary" },
    ],
    plans: ["Weekly Bible check-ins", "Monthly pastoral meetings"],
    actions: ["Support congregation", "Visit members in need"],
    comments: [
      { name: "Alice", text: "Great department for spiritual guidance!" },
    ],
  },
  {
    id: 2,
    name: "Youth Ministry",
    president: "Ms. Jane Smith",
    est: "2010",
    description: "Engaging youth with activities and mentorship programs.",
    members: ["Tom", "Lily", "Sam", "Anna"],
    committee: [
      { role: "President", name: "Tom" },
      { role: "Vice President", name: "Lily" },
      { role: "Secretary", name: "Sam" },
      { role: "Treasurer", name: "Anna" },
    ],
    plans: ["Youth weekend retreats", "Mentorship sessions"],
    actions: ["Organize events", "Provide counseling"],
    comments: [],
  },
  {
    id: 3,
    name: "Choir",
    president: "Mr. Samuel Lee",
    est: "2005",
    description: "Leading worship through music and choir performances.",
    members: ["Anna", "John", "Peter", "Maria"],
    committee: [
      { role: "President", name: "Samuel" },
      { role: "Vice President", name: "Anna" },
      { role: "Secretary", name: "John" },
      { role: "Treasurer", name: "Peter" },
    ],
    plans: ["Weekly practice", "Seasonal performances"],
    actions: ["Lead worship", "Participate in events"],
    comments: [],
  },
  {
    id: 4,
    name: "Bible Study",
    president: "Mrs. Emily Brown",
    est: "2012",
    description: "Facilitating Bible study groups and discussions.",
    members: ["Alice", "Mark", "David", "Sophia"],
    committee: [
      { role: "President", name: "Emily" },
      { role: "Vice President", name: "Mark" },
      { role: "Secretary", name: "David" },
      { role: "Treasurer", name: "Sophia" },
    ],
    plans: ["Weekly study sessions", "Monthly discussion forums"],
    actions: ["Lead study groups", "Prepare study materials"],
    comments: [],
  },
  {
    id: 5,
    name: "Community Outreach",
    president: "Mr. Michael Green",
    est: "2008",
    description: "Serving the local community through various initiatives.",
    members: ["Rachel", "James", "Tom", "Linda"],
    committee: [
      { role: "President", name: "Michael" },
      { role: "Vice President", name: "Rachel" },
      { role: "Secretary", name: "James" },
      { role: "Treasurer", name: "Tom" },
    ],
    plans: ["Monthly community events", "Charity drives"],
    actions: ["Organize outreach programs", "Coordinate volunteers"],
    comments: [],
  },
  {
    id: 6,
    name: "Education",
    president: "Dr. Angela White",
    est: "2015",
    description: "Providing educational programs and workshops.",
    members: ["Laura", "Eric", "Daniel", "Martha"],
    committee: [
      { role: "President", name: "Angela" },
      { role: "Vice President", name: "Laura" },
      { role: "Secretary", name: "Eric" },
      { role: "Treasurer", name: "Daniel" },
    ],
    plans: ["Weekly workshops", "Annual training programs"],
    actions: ["Provide education", "Organize seminars"],
    comments: [],
  },
  {
    id: 7,
    name: "Events",
    president: "Ms. Rachel Black",
    est: "2018",
    description: "Organizing church events, conferences, and gatherings.",
    members: ["Olivia", "Jack", "Sophia", "Leo"],
    committee: [
      { role: "President", name: "Rachel" },
      { role: "Vice President", name: "Olivia" },
      { role: "Secretary", name: "Jack" },
      { role: "Treasurer", name: "Sophia" },
    ],
    plans: ["Annual conferences", "Community events"],
    actions: ["Plan events", "Manage logistics"],
    comments: [],
  },
  {
    id: 8,
    name: "Counseling",
    president: "Dr. Kevin Gray",
    est: "2013",
    description: "Offering emotional and mental health counseling services.",
    members: ["Nina", "Tom", "Eric", "Lucy"],
    committee: [
      { role: "President", name: "Kevin" },
      { role: "Vice President", name: "Nina" },
      { role: "Secretary", name: "Tom" },
      { role: "Treasurer", name: "Eric" },
    ],
    plans: ["One-on-one sessions", "Support groups"],
    actions: ["Provide counseling", "Host support workshops"],
    comments: [],
  },
];
