export const weeks = [
  {
    weekNo: 1,
    date: "Jan 1 - Jan 7, 2025",
    name: "Faith & Beginnings",
    theme: "Starting the Year with God",
    verse:
      "Proverbs 3:5-6 — 'Trust in the Lord with all your heart…'",
    purpose: "To begin the year grounded in faith and trust in God.",
    plans: [
      "Monday: Morning Devotion & Prayer",
      "Wednesday: Bible Study on Faith",
      "Friday: Community Outreach",
      "Sunday: Worship Service & Thanksgiving",
    ],
    icon: "🌅", // sunrise for new beginnings
  },
  {
    weekNo: 2,
    date: "Jan 8 - Jan 14, 2025",
    name: "Love & Compassion",
    theme: "Showing Christ’s Love",
    verse: "1 Corinthians 13:4-7 — 'Love is patient, love is kind…'",
    purpose: "To cultivate love and compassion towards others.",
    plans: [
      "Tuesday: Volunteer at Local Shelter",
      "Thursday: Prayer for Neighbors",
      "Saturday: Family Fellowship",
      "Sunday: Worship & Praise",
    ],
    icon: "❤️",
  },
  {
    weekNo: 3,
    date: "Jan 15 - Jan 21, 2025",
    name: "Prayer & Strength",
    theme: "Drawing Strength Through Prayer",
    verse: "Philippians 4:6 — 'Do not be anxious about anything…'",
    purpose: "To strengthen reliance on God through prayer.",
    plans: [
      "Monday: Evening Prayer Chain",
      "Wednesday: Bible Study",
      "Friday: Personal Devotion",
      "Sunday: Thanksgiving Service",
    ],
    icon: "🙏",
  },
  {
    weekNo: 4,
    date: "Jan 22 - Jan 28, 2025",
    name: "Service & Humility",
    theme: "Serving Others in Humility",
    verse: "Mark 10:45 — 'For even the Son of Man did not come…'",
    purpose: "To encourage humble service and selflessness.",
    plans: [
      "Tuesday: Community Clean-Up",
      "Thursday: Food Distribution",
      "Saturday: Youth Outreach",
      "Sunday: Worship Service",
    ],
    icon: "🤝",
  },
  {
    weekNo: 5,
    date: "Jan 29 - Feb 4, 2025",
    name: "Hope & Perseverance",
    theme: "Holding On to Hope",
    verse: "Romans 12:12 — 'Be joyful in hope, patient in affliction…'",
    purpose: "To strengthen perseverance through hope in God.",
    plans: [
      "Monday: Morning Devotion",
      "Wednesday: Testimony Sharing",
      "Friday: Fellowship Night",
      "Sunday: Worship & Reflection",
    ],
    icon: "🌈",
  },
  {
    weekNo: 6,
    date: "Feb 5 - Feb 11, 2025",
    name: "Faith in Action",
    theme: "Living Out Our Faith",
    verse: "James 2:17 — 'Faith by itself, if it is not accompanied…'",
    purpose: "To practice faith through tangible actions.",
    plans: [
      "Tuesday: Charity Drive",
      "Thursday: Bible Study",
      "Saturday: Youth Leadership Training",
      "Sunday: Worship Service",
    ],
    icon: "💪",
  },
  {
    weekNo: 7,
    date: "Feb 12 - Feb 18, 2025",
    name: "Gratitude & Praise",
    theme: "Giving Thanks Always",
    verse: "1 Thessalonians 5:18 — 'Give thanks in all circumstances…'",
    purpose: "To cultivate a heart of gratitude.",
    plans: [
      "Monday: Prayer & Praise",
      "Wednesday: Community Thanksgiving",
      "Friday: Worship Night",
      "Sunday: Morning Service",
    ],
    icon: "🎶",
  },
  {
    weekNo: 8,
    date: "Feb 19 - Feb 25, 2025",
    name: "Unity & Fellowship",
    theme: "Growing Together in Christ",
    verse: "Psalm 133:1 — 'How good and pleasant it is when God’s people live together in unity!'",
    purpose: "To strengthen unity and fellowship within the church.",
    plans: [
      "Tuesday: Small Group Meetings",
      "Thursday: Bible Study",
      "Saturday: Fellowship Event",
      "Sunday: Joint Worship",
    ],
    icon: "🤗",
  },
  {
    weekNo: 9,
    date: "Feb 26 - Mar 4, 2025",
    name: "Guidance & Wisdom",
    theme: "Seeking God’s Direction",
    verse: "James 1:5 — 'If any of you lacks wisdom, you should ask God…'",
    purpose: "To seek God’s wisdom in daily decisions.",
    plans: [
      "Monday: Morning Devotion",
      "Wednesday: Leadership Bible Study",
      "Friday: Prayer for Guidance",
      "Sunday: Sermon Reflection",
    ],
    icon: "🧭",
  },
  {
    weekNo: 10,
    date: "Mar 5 - Mar 11, 2025",
    name: "Joy & Celebration",
    theme: "Rejoicing in the Lord",
    verse: "Psalm 100:1-2 — 'Shout for joy to the Lord…'",
    purpose: "To celebrate God’s goodness and rejoice in faith.",
    plans: [
      "Tuesday: Praise & Worship Night",
      "Thursday: Community Celebration",
      "Saturday: Youth Event",
      "Sunday: Worship & Thanksgiving",
    ],
    icon: "🎉",
  },
  {
    weekNo: 11,
    date: "Mar 12 - Mar 18, 2025",
    name: "Stewardship & Giving",
    theme: "Managing God’s Blessings",
    verse: "2 Corinthians 9:7 — 'Each of you should give what you have decided…'",
    purpose: "To encourage responsible stewardship and generosity.",
    plans: [
      "Monday: Bible Study on Giving",
      "Wednesday: Charity Event",
      "Friday: Personal Reflection",
      "Sunday: Worship & Offering",
    ],
    icon: "💰",
  },
  {
    weekNo: 12,
    date: "Mar 19 - Mar 25, 2025",
    name: "Peace & Reconciliation",
    theme: "Living in Harmony",
    verse: "Matthew 5:9 — 'Blessed are the peacemakers…'",
    purpose: "To promote peace and reconciliation in the community.",
    plans: [
      "Tuesday: Mediation & Prayer",
      "Thursday: Community Discussion",
      "Saturday: Fellowship Activities",
      "Sunday: Worship Service",
    ],
    icon: "🕊️",
  },
];
